# Generated by Django 3.1.2 on 2020-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201017_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEditRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('target_value', models.CharField(blank=True, max_length=4, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('O', 'open'), ('C', 'closed'), ('A', 'approved')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
