# Generated by Django 3.1.2 on 2020-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201017_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studenteditrequest',
            name='target_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
