# Generated by Django 3.1.2 on 2020-10-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201017_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteditrequest',
            name='status',
            field=models.CharField(choices=[('O', 'open'), ('C', 'closed'), ('A', 'approved')], default='O', max_length=10),
        ),
    ]
